"""changed JobDoctor model

Revision ID: 0bd963ccf3a6
Revises: 566e04cb86ca
Create Date: 2020-03-25 17:41:49.144819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd963ccf3a6'
down_revision = '566e04cb86ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incartjobs', 'job_started')
    op.drop_column('incartjobs', 'request_answer_id')
    op.drop_column('incartjobs', 'answered')
    op.drop_column('incartjobs', 'job_finished')
    op.drop_column('incartjobs', 'job_start_id')
    op.drop_column('incartjobs', 'request_time_estimate')
    op.drop_column('incartjobs', 'candidate_id')
    op.drop_column('incartjobs', 'job_time_estimate')
    op.drop_column('incartjobs', 'request_started')
    op.drop_column('incartjobs', 'job_finish_id')
    op.drop_column('incartjobs', 'request_id')
    op.add_column('jobdoctors', sa.Column('job_finished', sa.DateTime(), nullable=True))
    op.drop_column('jobdoctors', 'candidate_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobdoctors', sa.Column('candidate_id', sa.INTEGER(), nullable=True))
    op.drop_column('jobdoctors', 'job_finished')
    op.add_column('incartjobs', sa.Column('request_id', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('job_finish_id', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('request_started', sa.DATETIME(), nullable=True))
    op.add_column('incartjobs', sa.Column('job_time_estimate', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('candidate_id', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('request_time_estimate', sa.DATETIME(), nullable=True))
    op.add_column('incartjobs', sa.Column('job_start_id', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('job_finished', sa.DATETIME(), nullable=True))
    op.add_column('incartjobs', sa.Column('answered', sa.DATETIME(), nullable=True))
    op.add_column('incartjobs', sa.Column('request_answer_id', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('job_started', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
