"""updated IncartJob model

Revision ID: 0d66fc6d5ad1
Revises: 0bd963ccf3a6
Create Date: 2020-03-26 14:29:08.076594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d66fc6d5ad1'
down_revision = '0bd963ccf3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incartjobs', sa.Column('comment', sa.String(length=512), nullable=True))
    op.add_column('incartjobs', sa.Column('desc_text', sa.String(length=512), nullable=True))
    op.add_column('incartjobs', sa.Column('good_len', sa.Integer(), nullable=True))
    op.add_column('incartjobs', sa.Column('id_inw', sa.Integer(), nullable=True))
    op.add_column('incartjobs', sa.Column('info_type', sa.String(length=64), nullable=True))
    op.add_column('incartjobs', sa.Column('len_type', sa.Integer(), nullable=True))
    op.add_column('incartjobs', sa.Column('link_continue', sa.String(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('link_pdf', sa.String(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('link_view', sa.String(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('pat_id', sa.String(length=64), nullable=True))
    op.add_column('incartjobs', sa.Column('perm_link', sa.String(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('rec_len', sa.Integer(), nullable=True))
    op.add_column('incartjobs', sa.Column('signals', sa.String(), nullable=True))
    op.add_column('incartjobs', sa.Column('start_dt', sa.String(length=32), nullable=True))
    op.add_column('incartjobs', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('incartjobs', sa.Column('state_changed', sa.DateTime(), nullable=True))
    op.add_column('incartjobs', sa.Column('state_info', sa.String(length=512), nullable=True))
    op.add_column('incartjobs', sa.Column('worker_info', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incartjobs', 'worker_info')
    op.drop_column('incartjobs', 'state_info')
    op.drop_column('incartjobs', 'state_changed')
    op.drop_column('incartjobs', 'state')
    op.drop_column('incartjobs', 'start_dt')
    op.drop_column('incartjobs', 'signals')
    op.drop_column('incartjobs', 'rec_len')
    op.drop_column('incartjobs', 'perm_link')
    op.drop_column('incartjobs', 'pat_id')
    op.drop_column('incartjobs', 'link_view')
    op.drop_column('incartjobs', 'link_pdf')
    op.drop_column('incartjobs', 'link_continue')
    op.drop_column('incartjobs', 'len_type')
    op.drop_column('incartjobs', 'info_type')
    op.drop_column('incartjobs', 'id_inw')
    op.drop_column('incartjobs', 'good_len')
    op.drop_column('incartjobs', 'desc_text')
    op.drop_column('incartjobs', 'comment')
    # ### end Alembic commands ###
