"""Added JobDoctor model

Revision ID: 16d6f1d19fa1
Revises: 24252c437c72
Create Date: 2020-03-24 16:59:34.406318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d6f1d19fa1'
down_revision = '24252c437c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobdoctors',
    sa.Column('job_id', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['incartjobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobdoctors')
    # ### end Alembic commands ###
