"""Create table incartjobs

Revision ID: 24252c437c72
Revises: 46d50f604166
Create Date: 2020-03-15 19:39:13.248808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24252c437c72'
down_revision = '46d50f604166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incartjobs',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('snippet', sa.String(length=512), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('request_started', sa.DateTime(), nullable=True),
    sa.Column('request_time_estimate', sa.DateTime(), nullable=True),
    sa.Column('request_answer_id', sa.Integer(), nullable=True),
    sa.Column('answered', sa.DateTime(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('job_start_id', sa.Integer(), nullable=True),
    sa.Column('job_started', sa.DateTime(), nullable=True),
    sa.Column('job_time_estimate', sa.Integer(), nullable=True),
    sa.Column('job_finish_id', sa.Integer(), nullable=True),
    sa.Column('job_finished', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incartjobs')
    # ### end Alembic commands ###
