"""modofied incartjobs table

Revision ID: 50eb87a4ac2a
Revises: f20581fef338
Create Date: 2020-07-28 11:16:26.282530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eb87a4ac2a'
down_revision = 'f20581fef338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incartjobs', sa.Column('enc_error', sa.String(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('file_decrypt', sa.String(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('file_encrypt', sa.String(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('incartjobs', sa.Column('report', sa.String(length=128), nullable=True))
    op.drop_column('incartjobs', 'state_info')
    op.drop_column('incartjobs', 'signals')
    op.drop_column('incartjobs', 'info_type')
    op.drop_column('incartjobs', 'id_inw')
    op.drop_column('incartjobs', 'link_continue')
    op.drop_column('incartjobs', 'link_view')
    op.drop_column('incartjobs', 'rec_len')
    op.drop_column('incartjobs', 'good_len')
    op.drop_column('incartjobs', 'worker_info')
    op.drop_column('incartjobs', 'comment')
    op.drop_column('incartjobs', 'state')
    op.drop_column('incartjobs', 'start_dt')
    op.drop_column('incartjobs', 'pat_id')
    op.drop_column('incartjobs', 'state_changed')
    op.drop_column('incartjobs', 'concl_parts')
    op.drop_column('incartjobs', 'len_type')
    op.drop_column('incartjobs', 'desc_text')
    op.drop_column('incartjobs', 'link_analyze')
    op.drop_column('incartjobs', 'link_pdf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incartjobs', sa.Column('link_pdf', sa.VARCHAR(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('link_analyze', sa.VARCHAR(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('desc_text', sa.VARCHAR(length=512), nullable=True))
    op.add_column('incartjobs', sa.Column('len_type', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('concl_parts', sa.VARCHAR(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('state_changed', sa.DATETIME(), nullable=True))
    op.add_column('incartjobs', sa.Column('pat_id', sa.VARCHAR(length=64), nullable=True))
    op.add_column('incartjobs', sa.Column('start_dt', sa.VARCHAR(length=32), nullable=True))
    op.add_column('incartjobs', sa.Column('state', sa.VARCHAR(length=64), nullable=True))
    op.add_column('incartjobs', sa.Column('comment', sa.VARCHAR(length=512), nullable=True))
    op.add_column('incartjobs', sa.Column('worker_info', sa.VARCHAR(length=512), nullable=True))
    op.add_column('incartjobs', sa.Column('good_len', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('rec_len', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('link_view', sa.VARCHAR(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('link_continue', sa.VARCHAR(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('id_inw', sa.INTEGER(), nullable=True))
    op.add_column('incartjobs', sa.Column('info_type', sa.VARCHAR(length=64), nullable=True))
    op.add_column('incartjobs', sa.Column('signals', sa.VARCHAR(length=128), nullable=True))
    op.add_column('incartjobs', sa.Column('state_info', sa.VARCHAR(length=512), nullable=True))
    op.drop_column('incartjobs', 'report')
    op.drop_column('incartjobs', 'order_id')
    op.drop_column('incartjobs', 'file_encrypt')
    op.drop_column('incartjobs', 'file_decrypt')
    op.drop_column('incartjobs', 'enc_error')
    # ### end Alembic commands ###
