"""IncartJom modell Column restart added

Revision ID: f20581fef338
Revises: e32c709591a4
Create Date: 2020-04-02 16:12:12.603922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20581fef338'
down_revision = 'e32c709591a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incartjobs', sa.Column('restart', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incartjobs', 'restart')
    # ### end Alembic commands ###
